module: 'Models.Resnets'
model: 'cifar_resnet1001'
model_parameters: {} 
train_parameters:
    logdir: 'pon_11'
    run_name: 'cifar_resnet1001'
    log_interval: 200
    val_interval: 2000
    batch_size: 32
skip_error_test: True
